version: '3.8'

services:
  users-service:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./users:/application
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-network

  delivery-service:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./delivery:/application
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
